// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdb0eIeBf8jg-nNzop2heJ2XM8Gxd5rWI',
    appId: '1:184683898997:web:954906298c5a26af11703c',
    messagingSenderId: '184683898997',
    projectId: 'my-apps-1a24e',
    authDomain: 'my-apps-1a24e.firebaseapp.com',
    databaseURL: 'https://my-apps-1a24e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-apps-1a24e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAUQUrgUUMJjKQ9xhGr93hJQ4VKTcXtrA',
    appId: '1:184683898997:android:26f9822e28b8d21311703c',
    messagingSenderId: '184683898997',
    projectId: 'my-apps-1a24e',
    databaseURL: 'https://my-apps-1a24e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-apps-1a24e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeXRAFHAqKh0sxW47LF5dVWDMXvo60Dh8',
    appId: '1:184683898997:ios:6bead916dab4273b11703c',
    messagingSenderId: '184683898997',
    projectId: 'my-apps-1a24e',
    databaseURL: 'https://my-apps-1a24e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-apps-1a24e.firebasestorage.app',
    iosClientId: '184683898997-oc13m8bi2h9mfkt15bmr49o1ipfqlohd.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeXRAFHAqKh0sxW47LF5dVWDMXvo60Dh8',
    appId: '1:184683898997:ios:6bead916dab4273b11703c',
    messagingSenderId: '184683898997',
    projectId: 'my-apps-1a24e',
    databaseURL: 'https://my-apps-1a24e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-apps-1a24e.firebasestorage.app',
    iosClientId: '184683898997-oc13m8bi2h9mfkt15bmr49o1ipfqlohd.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKiocXmnZ6xY4DkAk_t6H1xkp0rq99Tys',
    appId: '1:184683898997:web:8e14aab620f60c1c11703c',
    messagingSenderId: '184683898997',
    projectId: 'my-apps-1a24e',
    authDomain: 'my-apps-1a24e.firebaseapp.com',
    databaseURL: 'https://my-apps-1a24e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-apps-1a24e.firebasestorage.app',
  );
}
